global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'config-server:8888'
          - 'discovery-server:8761'
          - 'api-gateway:8080'
          - 'cliente-service:8081'
          - 'peca-service:8082'
          - 'representante-service:8083'