spring:
  application:
    name: cliente-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
<<<<<<< HEAD

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
=======
>>>>>>> 8c27eb803ecf38ee0913ab81cf7f3495d6f9606f
