server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/microservices-cs
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/microservices-cs/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: cliente-service
              uri: lb://cliente-service
              predicates:
                - Path=/clientes/**
              filters:
                - TokenRelay=
            - id: peca-service
              uri: lb://peca-service
              predicates:
                - Path=/pecas/**
              filters:
                - TokenRelay=
            - id: representante-service
              uri: lb://representante-service
              predicates:
                - Path=/representantes/**
              filters:
                - TokenRelay=

scalar:
  enabled: true
  url: /v3/api-docs
  dark-mode: true
  path: /docs
  theme: deep_space
